theme: minima

minima:
  skin: solarized-light

author:
  name: ZHENG Robert
  #email: no.spam@hotmail.dev

page_created: 2024-08-23
page_url: https://pages.github.com/Zheng-Bote/gha-gh-pages_minima
page_desc: Example GH-Page with Jeckyll Minima-Theme

header_pages:
  - about.md
  - links.md
